import AdminLayout from "../../components/admin/AdminLayout";
import { useEffect, useState } from "react";
import { db } from "../../firebaseConfig";
import { collection, getDocs } from "firebase/firestore";
import { jsPDF } from "jspdf";


function Reports() {


const [report,setReport] = useState({

total:0,
verified:0,
pending:0,
rejected:0

});


const [loading,setLoading]=useState(true);



useEffect(()=>{

loadReport();

},[]);



const loadReport = async()=>{


try{


const snapshot = await getDocs(
collection(db,"users")
);



let total=0;
let verified=0;
let pending=0;
let rejected=0;



snapshot.forEach((doc)=>{


const user = doc.data();



if(user.role !== "admin" && user.emailVerified === true){


total++;


const status =
(user.status || "")
.toLowerCase()
.trim();



if(status==="verified"){

verified++;

}


else if(status==="pending"){

pending++;

}


else if(status==="rejected"){

rejected++;

}


}



});



setReport({

total,
verified,
pending,
rejected

});



}

catch(error){

console.log(error);

}

finally{

setLoading(false);

}


};





const downloadReport = ()=>{


const pdf = new jsPDF();



pdf.setFontSize(18);

pdf.text(
"National e-ID Citizen Report",
20,
20
);



pdf.setFontSize(12);



pdf.text(
`Total Citizens : ${report.total}`,
20,
45
);



pdf.text(
`Verified Users : ${report.verified}`,
20,
55
);



pdf.text(
`Pending Requests : ${report.pending}`,
20,
65
);



pdf.text(
`Rejected Users : ${report.rejected}`,
20,
75
);



pdf.text(
"Generated by Admin Panel",
20,
95
);



pdf.save(
"Citizen_Report.pdf"
);



};





return(

<AdminLayout>


<h2 className="page-title">
Reports
</h2>



{
loading ?

<h3>
Loading Reports...
</h3>


:

<div className="cardContainer">



<div className="card">

<h4>
Total Citizens
</h4>

<h2>
{report.total}
</h2>

</div>



<div className="card">

<h4>
Verified
</h4>

<h2>
{report.verified}
</h2>

</div>




<div className="card">

<h4>
Pending
</h4>

<h2>
{report.pending}
</h2>

</div>




<div className="card">

<h4>
Rejected
</h4>

<h2>
{report.rejected}
</h2>

</div>



</div>

}



<br/>


<button
className="approve-btn"
onClick={downloadReport}
>

Download PDF Report

</button>



</AdminLayout>

);


}


export default Reports;